version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data

  prisma-studio:
    ports:
      - "5555:5555"
    build:
      context: .
      dockerfile: prisma/Dockerfile
    env_file:
      .env
    volumes:
      - ./prisma:/app/prisma

volumes:
  db:
    driver: local
