version: "3.8"
services:
  web:
    image: oven/bun:1
    command: sh -c "bun install && bunx prisma db push --accept-data-loss && bun run dev"
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data

  prisma-studio:
    ports:
      - "5555:5555"
    build:
      context: .
      dockerfile: prisma/Dockerfile
    env_file:
      .env
    volumes:
      - ./prisma:/app/prisma

volumes:
  db:
    driver: local
