import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "@/styles/globals.css"
import { cn } from "@/lib/utils"
import { Sidebar } from "@/components/sidebar/sidebar"
import Navbar from "@/components/navbar/navbar"

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.variable
        )}
      >
        <div className="grid h-screen max-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr] grid-rows-[auto,1fr] lg:grid-rows-[60px_1fr]">
          <Sidebar />
          <Navbar />

          <main className="p-4">{children}</main>
        </div>
      </body>
    </html>
  )
}
